<a href="https://colab.research.google.com/github/171473/Advanced-Software-System-Lab/blob/master/Assignement_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ans1

In [ ]:
import numpy as np
import numpy as np
x = np.arange(12, 38)
print("Original array")
print(x)
print("Reverse array")
x = x[::-1]
print(x)

Original array
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


ANS2.

In [ ]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


Ans3

In [ ]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")

print(result1)


original matrix
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multiplication:
[[1 2]
 [3 4]]


ANS4

In [ ]:
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix")
print(m)
result = np.trace(m)
print("Sum of diagnol element is ")
print(result)

Original matrix
[[0 1 2]
 [3 4 5]]
Sum of diagnol element is 
4


ANS5

In [ ]:
import numpy as np
x = np.random.normal(size=5)
print(x)

[-0.86858419  1.53505564 -0.2502704  -1.05846615 -1.07023422]


ANS6

In [ ]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.38680548 0.42505106 0.64284613 0.51262293 0.07111451]
 [0.69826361 0.01091028 0.72082102 0.13604114 0.83349897]
 [0.17416807 0.06236294 0.57416663 0.47414508 0.71894499]
 [0.83031553 0.95465868 0.57468405 0.20765753 0.44896018]
 [0.82945895 0.81660907 0.61917425 0.43519755 0.92826186]]
Minimum and Maximum Values:
0.010910278868246137 0.9546586791239016


ANS7

In [ ]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
print(y)

Original array: 
[[0.67747374 0.80103161 0.19202306 0.94439832]
 [0.75121721 0.32286749 0.63909931 0.17866355]
 [0.9338282  0.327164   0.79326837 0.29530389]
 [0.62851017 0.58431834 0.27335844 0.26417797]
 [0.39861576 0.86334456 0.38250075 0.07331328]
 [0.20062806 0.27724575 0.39589574 0.04774252]
 [0.80981054 0.17718297 0.03638104 0.4406314 ]
 [0.35558277 0.55641882 0.01603325 0.81039991]
 [0.92608981 0.2626384  0.37329988 0.94557566]
 [0.86728186 0.15506373 0.08032288 0.36844008]]
First 5 rows of the above array:
[[0.67747374 0.80103161 0.19202306 0.94439832]
 [0.75121721 0.32286749 0.63909931 0.17866355]
 [0.9338282  0.327164   0.79326837 0.29530389]
 [0.62851017 0.58431834 0.27335844 0.26417797]
 [0.39861576 0.86334456 0.38250075 0.07331328]]


ANS8

In [ ]:
import numpy as np
a= np.random.random((10,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.7436343  0.90421836 0.14049957 0.36243269 0.69329391
  0.8405199  0.70391598 0.71170645 0.93024151]
 [0.7436343  0.         0.16076467 0.8836772  0.74740245 0.17125922
  0.72012494 0.34710378 0.29296446 0.19503948]
 [0.90421836 0.16076467 0.         1.04414351 0.8889104  0.27292026
  0.78222283 0.43614701 0.38068972 0.05997763]
 [0.14049957 0.8836772  1.04414351 0.         0.40751141 0.827974
  0.92138338 0.83542522 0.84640949 1.06925492]
 [0.36243269 0.74740245 0.8889104  0.40751141 0.         0.62221445
  0.52574685 0.86661004 0.85084537 0.89167476]
 [0.69329391 0.17125922 0.27292026 0.827974   0.62221445 0.
  0.54930736 0.4855678  0.4366457  0.26957677]
 [0.8405199  0.72012494 0.78222283 0.92138338 0.52574685 0.54930736
  0.         1.01067772 0.96885476 0.74921108]
 [0.70391598 0.34710378 0.43614701 0.83542522 0.86661004 0.4855678
  1.01067772 0.         0.05588665 0.49394999]
 [0.71170645 0.29296446 0.38068972 0.84640949 0.85084537 0.4366457
  0.96885476 0.05588665 

ANS9

In [ ]:
import numpy as np
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height'))  

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


ANS10

In [ ]:

import numpy as np
nums = np.array([70, 50, 20, 30, -11, 60, 50, 40])
print("Original array:")
print(nums)
print("\nAfter partitioning on 4 the position:")
print(np.partition(nums, 4))

Original array:
[ 70  50  20  30 -11  60  50  40]

After partitioning on 4 the position:
[-11  30  20  40  50  50  60  70]


ANS11

In [ ]:
import numpy as np
x = np.arange(6)
print("\nOriginal array:")
print(x)
r1 = np.mean(x)
r2 = np.average(x)
assert np.allclose(r1, r2)
print("\nMean: ", r1)
r1 = np.std(x)
r2 = np.sqrt(np.mean((x - np.mean(x)) ** 2 ))
assert np.allclose(r1, r2)
print("\nstd: ", 1)
r1= np.var(x)
r2 = np.mean((x - np.mean(x)) ** 2 )
assert np.allclose(r1, r2)
print("\nvariance: ", r1)


Original array:
[0 1 2 3 4 5]

Mean:  2.5

std:  1

variance:  2.9166666666666665


ANS12

In [ ]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


ANS13

In [ ]:
import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCross-correlation of the said arrays:\n",np.cov(x, y))


Original array1:
[0 1 3]

Original array1:
[2 4 5]

Cross-correlation of the said arrays:
 [[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


ANS14

In [ ]:
import numpy as np
print("March, 2017")
print(np.arange('2017-03', '2017-04', dtype='datetime64[D]'))

March, 2017
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


ANS15

In [ ]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-09-23
Today:  2020-09-24
Tomorrow:  2020-09-25


ANS16

In [ ]:
 import numpy as np
from datetime import datetime
dt = datetime.utcnow()
print("Current date:")
print(dt)
dt64 = np.datetime64(dt)
ts = (dt64 - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
print("Timestamp:")
print(ts)
print("UTC from Timestamp:")
print(datetime.utcfromtimestamp(ts))

Current date:
2020-09-24 19:26:55.185413
Timestamp:
1600975615.185413
UTC from Timestamp:
2020-09-24 19:26:55.185413


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  import sys
